# Generated by Django 3.0.3 on 2020-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
